# Generated by Django 5.1.2 on 2024-10-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_numberofpostedvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Numberofpostedvideo',
            new_name='coins',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
