# Generated by Django 5.1.2 on 2024-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_last_coin_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='No Name found this is a test', max_length=30, null=True),
        ),
    ]
